version: "3.8"

networks:
    laravel:

volumes:
    mysql:

services:
    # Webserver services
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        ports:
            - "8000:80"
        volumes:
            - ./src/:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel

    # PHP Services
    php:
        build:
            context: ./docker
            dockerfile: php.dockerfile
        container_name: php
        ports:
            - "9000:80"
        volumes:
            - ./src:/var/www/html
        networks:
            - laravel
    composer:
        image: composer:latest
        container_name: composer
        volumes:
            - ./src:/var/www/html
        working_dir: /var/www/html
        networks:
            - laravel
    artisan:
        build:
            context: ./docker
            dockerfile: php.dockerfile
        container_name: artisan
        volumes:
            - ./src:/var/www/html
        entrypoint: ['php', '/var/www/html/artisan']
        networks:
            - laravel

    # Javascript/Node Services
    npm:
        container_name: npm
        image: node:latest
        volumes:
            - ./src:/var/www/html
        entrypoint: [ 'npm', '--no-bin--links' ]
        working_dir: /var/www/html
        networks:
            - laravel

    # Database services
    redis:
        image: redis:latest
        container_name: redis
        restart: unless-stopped
        ports:
            - "6379:6379"
        networks:
            - laravel
    mysql:
        image: mysql:latest
        container_name: mysql
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        volumes:
            - mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: YOUR_DATABASE_NAME
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            SERVICE_TAG: mysql
            SERVICE_NAME: mysql
        networks:
            - laravel
    phpmyadmin:
        image: phpmyadmin:latest
        container_name: phpmyadmin
        ports:
            - "8080:80"
        environment:
            PMA_HOST: mysql
            PMA_USER: root
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        restart: unless-stopped
        networks:
            - laravel